import { StyleSheet, Dimensions, Platform } from 'react-native';
const { width } = Dimensions.get('window');
import { colors } from '../theme/colors';

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  header: {
    backgroundColor: colors.surface,
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e5e5',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logoContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoImage: {
    width: 120,
    height: 60,
  },
  logo: {
    width: 48,
    height: 48,
    backgroundColor: colors.primary,
    borderRadius: 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 4,
  },
  logoText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 12,
  },
  companyName: {
    fontSize: 10,
    color: '#666',
    fontWeight: '600',
  },
  headerSpacer: {
    width: 24,
  },
  titleSection: {
    backgroundColor: colors.surface,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e5e5',
    flexDirection: 'row',
    alignItems: 'center',
  },
  titleIcon: {
    width: 24,
    height: 24,
    backgroundColor: '#d1fae5',
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  titleText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  scrollView: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  mainContainer: {
    position: 'relative',
    paddingTop: 40,
  },
  navButton: {
    position: 'absolute',
    zIndex: 10,
    width: 40,
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  navButtonLeft: {
    left: 16,
    top: 180,
  },
  navButtonRight: {
    right: 16,
    top: 180,
  },
  profileContent: {
    alignItems: 'center',
    paddingHorizontal: 32,
  },
  profileImageContainer: {
    width: 180,
    height: 180,
    borderRadius: 90,
    overflow: 'hidden',
    marginBottom: 24,
    borderWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  profileImage: {
    width: '100%',
    height: '100%',
  },
  nameText: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1f2937',
    marginBottom: 4,
  },
  majorText: {
    fontSize: 16,
    fontWeight: 'bold',
    fontStyle: 'italic',
    color: '#1f2937',
    marginBottom: 12,
    textAlign: 'center',
    letterSpacing: 0.5,
  },
  studentId: {
    fontSize: 13,
    color: '#6b7280',
    marginBottom: 16,
  },
  initials: {
    fontSize: 56,
    fontWeight: 'bold',
    color: '#fff',
  },
  titleBadge: {
    fontSize: 16,
    fontWeight: '600',
    color: colors.primary,
    backgroundColor: '#d1fae5',
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 12,
    marginBottom: 8,
  },
  employeeId: {
    fontSize: 13,
    color: '#6b7280',
    marginBottom: 16,
  },
  description: {
    fontSize: 14,
    color: '#4b5563',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
    paddingHorizontal: 16,
  },
  socialContainer: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 32,
  },
  socialButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  socialWhatsapp: {
    backgroundColor: '#d1fae5',
  },
  socialLinkedIn: {
    backgroundColor: '#dbeafe',
  },
  socialFacebook: {
    backgroundColor: '#dbeafe',
  },
  dotsContainer: {
    marginTop: 24,
    width: '100%',
  },
  dotsScroll: {
    paddingHorizontal: 20,
    paddingVertical: 20,
    gap: 16,
    marginBottom: 40,
    alignItems: 'center',
  },
  dotButton: {
    alignItems: 'center',
    marginHorizontal: 4,
  },
  dot: {
    width: 40,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'hidden',
  },
  dotActive: {
    transform: [{ scale: 1.2 }],
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  dotInactive: {
    opacity: 0.6,
  },
  dotLabel: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  dotImage: {
    width: '100%',
    height: '100%',
  },
  dotInfo: {
    alignItems: 'center',
    marginTop: 6,
    maxWidth: 80,
  },
  dotName: {
    fontSize: 12,
    fontWeight: '600',
    color: '#1f2937',
    textAlign: 'center',
  },
  dotPosition: {
    fontSize: 10,
    color: '#6b7280',
    marginTop: 2,
    textAlign: 'center',
  },
  bottomNav: {
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#e5e5e5',
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 12,
    paddingBottom: 16,
  },
  navItem: {
    alignItems: 'center',
  },
});